name = "simulations"
version = "0.1.0"
license = "license"
author = "PSauerborn"
maintainer = "pascal.sauerborn@gmail.com"
copyright = "Copyright 2026, PSauerborn"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
toml-f = { git = "https://github.com/toml-f/toml-f", tag = "v0.4.3" }
csv-fortran = { git="https://github.com/jacobwilliams/csv-fortran.git", tag="3.0.0" }
